### ISSUE TITLE
autoprefixer-like browser support rules

### ISSUE THREAD

**Issue by jrencz** [jubalm/grunt-fontello#13]
Fontello generates a lot of data including some ie7 fixes and 4 font formats.
That's not always what is needed if a project supports only modern browsers - those browsers can get only `woff`, other formats may be omitted.

I described my case in the https://github.com/fontello/fontello/issues/338 which was closed as out of fontello scope.

I wonder if integrating browser support config (presumably, but not necessarily the one mentioned in the issue above used by autoprefixer) would be a welcome feature for grunt-fontello or should I try to implement this as a distinct task. What do you think?

**Comment by ericcornelissen** [comment]
🤔 

I personally don't think this is necessarily a desired feature for this package, for reasons similar to those given in the Fontello repository. But if you're still interested in this feature, please reopen with an outline of how you would implement the feature and how you would implement it as a distinct task 😄
