### ISSUE TITLE
Generated font-files corrupt, don't work in firefox

### ISSUE THREAD

**Issue by iggyvanlith** [jubalm/grunt-fontello#15]
The generated font-files seem corrupt. In firefox (32.0.3) the fonts don't display anymore. When using the fonts downloaded by hand from fontello they do work.

**Comment by Truffula** [comment]
I've found that occasionally the downloaded package has files which are incomplete (e.g. 90% `_fontello-embedded.scss` is missing). Sometimes it works after several attempts; some days it seems to have no problems at all.

Grunt options:
```js
        fontello: {
            dist: {
                options: {
                    config: 'config/font/config.json',
                    fonts: 'public/assets/icons/fonts',
                    styles: 'app/styles/fontello',
                    scss: true,
                    force: true,
                }
            }
        },
```

**Comment by ericcornelissen** [comment]
This seems like a bug with the Fontello API to me 🤔

If anyone still experiences this issue, feel free to reopen with some details about your grunt-fontello task configuration and Fontello config file.
