### ISSUE TITLE
Fatal error: invalid signature: 0x3430345b

### ISSUE THREAD

**Issue by gfdickinson** [jubalm/grunt-fontello#18]
When running the grunt task, I get the following error:
Fatal error: invalid signature: 0x3430345b
Here is my config:
fontello: {
        dist: {
           options: {
                config : 'client/config.json',
                fonts  : 'client/fonts',
                scss   : true
            }
        }
    }

**Comment by SiamKreative** [comment]
Did you manage to get this solved @gfdickinson ? Same thing happening for me. What am I doing wrong @jubalm ?

```javascript
fontello: {
	dist: {
		options: {
			config: '<%= config.app %>/fontello.json',
			fonts: '<%= config.app %>/fonts',
			styles: '<%= config.app %>/styles',
			scss: true,
			force: true
		}
	}
},
```

**Comment by thomas-brx** [comment]
For me this was due to a syntax error in fontello.json.
0x3430345b is hex for 404[, "grunt fontello" was downloading a bad url:
```
http://fontello.com/Can't parse config data/get
```

**Comment by rluders** [comment]
similar error here. But I'm getting '[500] Internal Server Error'

**Comment by spAnser** [comment]
So what I have run into right now is that in the `config.json` if the name is blank

```
"name": "",
```

grunt-fontello seems to update that with an id

```
"name": "fc1a6fe4c6bb1988ed893cb4406af092",
```

However it appears that this id is not a permanent id and causes issues on subsequent runs.

My fix has been to empty out that name field anytime I run into this issue. Although this seems like it could be automated somehow or grunt-fontello could be updated to detect if the id is expired.

This is my assumption to how that name works. I didn't research it. However emptying that name field works for me. Maybe grunt-fontello shouldn't be updating that field in your json at all.

**Comment by ericcornelissen** [comment]
With #36 merged most of the problems described in this issue should be solved, so I will close it for now.

If anyone continues experiencing this issue, feel free to reopen with a description of your problem 🙂
