### ISSUE TITLE
How to get UID for json?

### ISSUE THREAD

**Issue by anik786** [jubalm/grunt-fontello#19]
when creating the json file, how do i find the uid for the glyphs. I could not find them on the website. thanks!

**Comment by bryce-gibson** [comment]
It's not the best way, but I usually download the font off the Fontello website (or a local mirror) and then extract the config.json from there, and then merge the downloaded config.json into my local config.json

If that makes sense? :-s

(I think it's also possible to use a DOM inspector to look at the `data-id` property for the icon, as I _think_ that's the UID (iirc))
