### ISSUE TITLE
Switching default icon dir

### ISSUE THREAD

**Issue by canfie1d** [jubalm/grunt-fontello#2]
Unless I am mistaken, since the sass files are generated with the json file, there is no way to specify where those files will be placed. The looks for the font files in ../font/ by default.

If you change this dir in the gruntfile to ../fonts/icons/ for example, the icon files are built in the wrong place and not found by the sass because it is still looking for them in ../font/

**Comment by ram89** [comment]
+1

**Comment by ericcornelissen** [comment]
Resolved with #12
